# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

title: "Alex's Blog"
email: 
description: >-
  A minimal Jekyll blog about gaming, gaming automation, AI systems, 
  and whatever I'm building next.
baseurl: "/conjured-blog"
url: "https://ConjureGanja.github.io"
github_username: ConjureGanja

# Build settings
theme: minima

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
